"""
LLM Service Module
------------------
This file handles interaction with the Large Language Model (LLM).
For now, it returns a simulated response.
"""

def get_llm_response(prompt: str) -> str:
    """
    Sends a prompt to the LLM and returns the response.

    Parameters:
    - prompt (str): The formatted prompt sent to the LLM

    Returns:
    - str: AI-generated response (dummy for now)
    """

    # Dummy AI response (Sprint 2 placeholder)
    response = (
        "Here is a suggested event plan based on your details:\n\n"
        "- Create a guest list and finalize the venue\n"
        "- Plan decorations according to the theme\n"
        "- Allocate budget wisely across food, decor, and logistics\n"
        "- Prepare a simple event timeline\n\n"
        "This plan is generated by the AI Event Planning Assistant."
    )

    return response
